memcg-fix-reclaimable-lru-check-in-memcg-fix2.patch
 memcg-fix-reclaimable-lru-check-in-memcg.patch
 causes following error with !CONFIG_NUMA.

> mmotm-2011-0630-1559/mm/memcontrol.c:1579: error: implicit declaration of function 'mem_cgroup_node_nr_file_lru_pages'
> mmotm-2011-0630-1559/mm/memcontrol.c:1583: error: implicit declaration of function 'mem_cgroup_node_nr_anon_lru_pages'
>

This patch fixes it by moving functions out of #ifdef.

Reported-by: Randy Dunlap <randy.dunlap@oracle.com>
Signed-off-by: KAMEZAWA Hiroyuki <kamezawa.hiroyu@jp.fujitsu.com>